# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cam.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_view(object):
    def setupUi(self, view):
        view.setObjectName("view")
        view.setWindowModality(QtCore.Qt.ApplicationModal)
        view.resize(887, 539)
        self.btnPlay = QtWidgets.QPushButton(view)
        self.btnPlay.setEnabled(False)
        self.btnPlay.setGeometry(QtCore.QRect(790, 470, 75, 23))
        self.btnPlay.setObjectName("btnPlay")
        self.btnTest = QtWidgets.QPushButton(view)
        self.btnTest.setGeometry(QtCore.QRect(790, 500, 75, 23))
        self.btnTest.setObjectName("btnTest")
        self.layoutWidget = QtWidgets.QWidget(view)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 77, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnWebcam = QtWidgets.QPushButton(self.layoutWidget)
        self.btnWebcam.setCheckable(False)
        self.btnWebcam.setChecked(False)
        self.btnWebcam.setAutoRepeat(False)
        self.btnWebcam.setAutoExclusive(False)
        self.btnWebcam.setAutoDefault(False)
        self.btnWebcam.setDefault(False)
        self.btnWebcam.setFlat(False)
        self.btnWebcam.setObjectName("btnWebcam")
        self.verticalLayout.addWidget(self.btnWebcam)
        self.btnLoad = QtWidgets.QPushButton(self.layoutWidget)
        self.btnLoad.setObjectName("btnLoad")
        self.verticalLayout.addWidget(self.btnLoad)
        spacerItem = QtWidgets.QSpacerItem(10, 22, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.power_slider = QtWidgets.QSlider(self.layoutWidget)
        self.power_slider.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.power_slider.setOrientation(QtCore.Qt.Vertical)
        self.power_slider.setObjectName("power_slider")
        self.horizontalLayout_2.addWidget(self.power_slider)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.power_label = QtWidgets.QLabel(self.layoutWidget)
        self.power_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.power_label.setAlignment(QtCore.Qt.AlignCenter)
        self.power_label.setObjectName("power_label")
        self.horizontalLayout_4.addWidget(self.power_label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btnExit = QtWidgets.QPushButton(self.layoutWidget)
        self.btnExit.setObjectName("btnExit")
        self.verticalLayout.addWidget(self.btnExit)
        self.formGroupBox = QtWidgets.QGroupBox(view)
        self.formGroupBox.setGeometry(QtCore.QRect(260, 20, 601, 431))
        self.formGroupBox.setObjectName("formGroupBox")
        self.screen_layout = QtWidgets.QFormLayout(self.formGroupBox)
        self.screen_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.screen_layout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.screen_layout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.screen_layout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.screen_layout.setObjectName("screen_layout")
        self.label = QtWidgets.QLabel(self.formGroupBox)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label.setMouseTracking(True)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.screen_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.setting_frame = QtWidgets.QFrame(view)
        self.setting_frame.setEnabled(True)
        self.setting_frame.setGeometry(QtCore.QRect(120, 40, 81, 241))
        self.setting_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setting_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setting_frame.setObjectName("setting_frame")
        self.formLayoutWidget = QtWidgets.QWidget(self.setting_frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 83, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 9)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.normal_radio = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.normal_radio.setEnabled(True)
        self.normal_radio.setCheckable(True)
        self.normal_radio.setChecked(True)
        self.normal_radio.setObjectName("normal_radio")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.normal_radio)
        self.gray_radio = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.gray_radio.setObjectName("gray_radio")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gray_radio)
        self.hsv_radio = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.hsv_radio.setObjectName("hsv_radio")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.hsv_radio)
        spacerItem2 = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.threshold_check = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.threshold_check.setObjectName("threshold_check")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.threshold_check)
        self.threshold_slider = QtWidgets.QSlider(self.formLayoutWidget)
        self.threshold_slider.setEnabled(False)
        self.threshold_slider.setOrientation(QtCore.Qt.Horizontal)
        self.threshold_slider.setObjectName("threshold_slider")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.threshold_slider)
        self.mode_frame = QtWidgets.QFrame(view)
        self.mode_frame.setEnabled(True)
        self.mode_frame.setGeometry(QtCore.QRect(130, 450, 411, 80))
        self.mode_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mode_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mode_frame.setObjectName("mode_frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.mode_frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 259, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.motion_hsv_radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.motion_hsv_radio.setChecked(True)
        self.motion_hsv_radio.setObjectName("motion_hsv_radio")
        self.horizontalLayout.addWidget(self.motion_hsv_radio)
        self.motion_gray_radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.motion_gray_radio.setObjectName("motion_gray_radio")
        self.horizontalLayout.addWidget(self.motion_gray_radio)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.btnMotion = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnMotion.setObjectName("btnMotion")
        self.verticalLayout_3.addWidget(self.btnMotion)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.btnBgSub = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnBgSub.setObjectName("btnBgSub")
        self.verticalLayout_6.addWidget(self.btnBgSub)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.mode_frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(260, 0, 131, 81))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.btnTracking = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnTracking.setObjectName("btnTracking")
        self.verticalLayout_9.addWidget(self.btnTracking)
        self.motion_frame = QtWidgets.QFrame(view)
        self.motion_frame.setGeometry(QtCore.QRect(110, 50, 91, 81))
        self.motion_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.motion_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.motion_frame.setObjectName("motion_frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.motion_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 81, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.motion_contour_check = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.motion_contour_check.setObjectName("motion_contour_check")
        self.verticalLayout_2.addWidget(self.motion_contour_check)
        self.motion_contour_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.motion_contour_slider.setEnabled(False)
        self.motion_contour_slider.setOrientation(QtCore.Qt.Horizontal)
        self.motion_contour_slider.setObjectName("motion_contour_slider")
        self.verticalLayout_2.addWidget(self.motion_contour_slider)
        self.bg_sub_frame = QtWidgets.QFrame(view)
        self.bg_sub_frame.setGeometry(QtCore.QRect(120, 60, 101, 211))
        self.bg_sub_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bg_sub_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bg_sub_frame.setObjectName("bg_sub_frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.bg_sub_frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 84, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bg_sub_contour_check = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.bg_sub_contour_check.setObjectName("bg_sub_contour_check")
        self.verticalLayout_4.addWidget(self.bg_sub_contour_check)
        self.bg_sub_contour_slider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.bg_sub_contour_slider.setOrientation(QtCore.Qt.Horizontal)
        self.bg_sub_contour_slider.setObjectName("bg_sub_contour_slider")
        self.verticalLayout_4.addWidget(self.bg_sub_contour_slider)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.bg_sub_threshold_check = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.bg_sub_threshold_check.setObjectName("bg_sub_threshold_check")
        self.verticalLayout_4.addWidget(self.bg_sub_threshold_check)
        self.bg_sub_threshold_slider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.bg_sub_threshold_slider.setOrientation(QtCore.Qt.Horizontal)
        self.bg_sub_threshold_slider.setObjectName("bg_sub_threshold_slider")
        self.verticalLayout_4.addWidget(self.bg_sub_threshold_slider)
        self.btnSetBg = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnSetBg.setObjectName("btnSetBg")
        self.verticalLayout_4.addWidget(self.btnSetBg)
        self.tracking_frame = QtWidgets.QFrame(view)
        self.tracking_frame.setGeometry(QtCore.QRect(110, 70, 91, 101))
        self.tracking_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tracking_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tracking_frame.setObjectName("tracking_frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tracking_frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 79, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnSelectTracking = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSelectTracking.setObjectName("btnSelectTracking")
        self.gridLayout_2.addWidget(self.btnSelectTracking, 0, 0, 1, 1)
        self.optical_flow_check = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.optical_flow_check.setObjectName("optical_flow_check")
        self.gridLayout_2.addWidget(self.optical_flow_check, 1, 0, 1, 1)

        self.retranslateUi(view)
        QtCore.QMetaObject.connectSlotsByName(view)

    def retranslateUi(self, view):
        _translate = QtCore.QCoreApplication.translate
        view.setWindowTitle(_translate("view", "Form"))
        self.btnPlay.setText(_translate("view", "Play"))
        self.btnTest.setText(_translate("view", "test"))
        self.btnWebcam.setText(_translate("view", "Webcam"))
        self.btnLoad.setText(_translate("view", "Load file"))
        self.power_label.setText(_translate("view", "power"))
        self.btnExit.setText(_translate("view", "Exit"))
        self.normal_radio.setText(_translate("view", "normal"))
        self.gray_radio.setText(_translate("view", "gray"))
        self.hsv_radio.setText(_translate("view", "hsv"))
        self.threshold_check.setText(_translate("view", "threshold"))
        self.label_2.setText(_translate("view", "motion detection:"))
        self.motion_hsv_radio.setText(_translate("view", "hsv"))
        self.motion_gray_radio.setText(_translate("view", "gray"))
        self.btnMotion.setText(_translate("view", "ON"))
        self.label_3.setText(_translate("view", "background subtraction:"))
        self.btnBgSub.setText(_translate("view", "ON"))
        self.label_6.setText(_translate("view", "tracking:"))
        self.btnTracking.setText(_translate("view", "ON"))
        self.motion_contour_check.setText(_translate("view", "Contours"))
        self.bg_sub_contour_check.setText(_translate("view", "Counters"))
        self.bg_sub_threshold_check.setText(_translate("view", "threshold"))
        self.btnSetBg.setText(_translate("view", "set background"))
        self.btnSelectTracking.setText(_translate("view", "Select"))
        self.optical_flow_check.setText(_translate("view", "optical flow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    view = QtWidgets.QWidget()
    ui = Ui_view()
    ui.setupUi(view)
    view.show()
    sys.exit(app.exec_())

